
services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: storycraft
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - storycraft-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: storycraft@example.com  # pgadmin 이메일
      PGADMIN_DEFAULT_PASSWORD: storycraft          # pgadmin 비밀번호
    ports:
      - "5050:80"
    networks:
      - storycraft-network

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    container_name: storycraft-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/storycraft
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres
    networks:
      - storycraft-network

  jenkins:
    build:
      context: ..
      dockerfile: docker/Dockerfile.jenkins
    container_name: jenkins
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      -  /var/run/docker.sock:/var/run/docker.sock
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"


networks:
  storycraft-network:
    driver: bridge

volumes:
  pgdata:
  jenkins_home:
