version: '3.8'

services:
  redis:
    image: redis:7.2
    container_name: storycraft-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped

  backend:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: storycraft-backend
    ports:
      - "8080:8080"
    depends_on:
      - redis
    restart: always
